// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;


public class TestingTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void seltestlinkedin() {
    // Test name: seltestlinkedin
    // Step # | name | target | value
    // 1 | open | / |
    driver.get("https://www.google.com/");
    // 2 | setWindowSize | 1440x845 |
    driver.manage().window().setSize(new Dimension(1440, 845));
    // 3 | click | name=q |
    driver.findElement(By.name("q")).click();
    // 4 | type | name=q | phillip eismark
    driver.findElement(By.name("q")).sendKeys("phillip eismark");
    // 5 | sendKeys | name=q | ${KEY_ENTER}
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    // 6 | runScript | window.scrollTo(0,106.66667175292969) |
    js.executeScript("window.scrollTo(0,106.66667175292969)");
    // 7 | click | css=.g:nth-child(1) .LC20lb |
    driver.findElement(By.cssSelector(".g:nth-child(1) .LC20lb")).click();
  }

  @Test
  public void testGoogleSearch() throws InterruptedException {
    WebDriver driver = new ChromeDriver();
    driver.get("http://www.google.com/");
    Thread.sleep(5000);  // Let the user actually see something!
    WebElement searchBox = driver.findElement(By.name("q"));
    searchBox.sendKeys("ChromeDriver");
    searchBox.submit();
    Thread.sleep(5000);  // Let the user actually see something!
    driver.quit();
  }

}